version: "3.6"

services:
  webserver:
    image: my-webserver
    environment:
      - TZ=${TIMEZONE:-Europe/Berlin}
    ports:
      - "${HTTP_PORT:-80}:80"
    deploy:
      resources:
        limits:
          memory: "100m"
    volumes:
      - ${HTMLSITE}:/var/www/html
    hostname: ${NAME:-webserver}
    container_name: ${NAME:-webserver}
